#!/usr/bin/env node
/**
 * Builds the bundled exercise catalog from free-exercise-db (public domain / Unlicense).
 *
 *   npm run build:catalog
 *
 * Writes two committed artifacts so the app builds with no network:
 *   assets/data/exercises.json  - the normalised catalog
 *   src/catalog/generated.ts    - enums + facet lists derived from the data
 *
 * Re-run this only when you want to pick up upstream changes; the diff is reviewable.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE =
  'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json';

/** Every muscle the upstream dataset uses. Order is anatomical-ish, for stable UI listing. */
const MUSCLES = [
  'neck',
  'traps',
  'shoulders',
  'chest',
  'biceps',
  'triceps',
  'forearms',
  'lats',
  'middle back',
  'lower back',
  'abdominals',
  'glutes',
  'quadriceps',
  'hamstrings',
  'adductors',
  'abductors',
  'calves',
];

const CATEGORIES = [
  'strength',
  'powerlifting',
  'olympic weightlifting',
  'strongman',
  'plyometrics',
  'stretching',
  'cardio',
];

const LEVELS = ['beginner', 'intermediate', 'expert'];
const FORCES = ['push', 'pull', 'static'];
const MECHANICS = ['compound', 'isolation'];

/**
 * Which numbers a set of this exercise records.
 * Derived so that planks and sprints aren't forced into a weight x reps shape.
 * Overridable per plan item in the app.
 */
function defaultSetKind(exercise) {
  // A static force is an isometric hold - planks, side bridges, plate pinches, most
  // stretches. You count seconds, not reps. This has to be checked before category,
  // because the dataset files Plank under "strength".
  if (exercise.force === 'static') return 'time';

  switch (exercise.category) {
    case 'cardio':
      return 'distance_time';
    case 'stretching':
      return 'time';
    case 'plyometrics':
      return 'reps';
    default:
      return exercise.equipment === 'body only' && exercise.category === 'strength'
        ? 'reps'
        : 'weight_reps';
  }
}

function assertEnum(value, allowed, field, exerciseId) {
  if (value === null || value === undefined) return null;
  if (!allowed.includes(value)) {
    throw new Error(`${exerciseId}: unexpected ${field} "${value}"`);
  }
  return value;
}

async function main() {
  process.stdout.write(`Fetching ${SOURCE}\n`);
  const res = await fetch(SOURCE);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching source dataset`);
  const raw = await res.json();
  if (!Array.isArray(raw) || raw.length === 0) throw new Error('Source dataset is empty');

  const seenIds = new Set();
  const equipmentSet = new Set();

  const exercises = raw.map((e) => {
    if (!e.id || !e.name) throw new Error(`Exercise missing id/name: ${JSON.stringify(e).slice(0, 120)}`);
    if (seenIds.has(e.id)) throw new Error(`Duplicate exercise id "${e.id}"`);
    seenIds.add(e.id);

    for (const m of [...e.primaryMuscles, ...e.secondaryMuscles]) {
      if (!MUSCLES.includes(m)) throw new Error(`${e.id}: unknown muscle "${m}"`);
    }
    assertEnum(e.category, CATEGORIES, 'category', e.id);
    assertEnum(e.level, LEVELS, 'level', e.id);
    assertEnum(e.force, FORCES, 'force', e.id);
    assertEnum(e.mechanic, MECHANICS, 'mechanic', e.id);
    if (e.equipment) equipmentSet.add(e.equipment);

    // Nine upstream entries (Clean and Press, Barbell Step Ups, ...) list a muscle as both
    // primary and secondary. Left alone, one set would credit that muscle 1.0 + 0.5 = 1.5
    // effective sets and quietly inflate the heatmap. Primary always wins.
    const primary = [...new Set(e.primaryMuscles)];
    const secondary = [...new Set(e.secondaryMuscles)].filter((m) => !primary.includes(m));

    const normalised = {
      id: e.id,
      name: e.name,
      category: e.category,
      level: e.level,
      force: e.force ?? null,
      mechanic: e.mechanic ?? null,
      equipment: e.equipment ?? null,
      primaryMuscles: primary,
      secondaryMuscles: secondary,
      instructions: e.instructions ?? [],
      // The upstream photographs are deliberately NOT carried over. Their copyright status
      // was never established (issues #2 and #12 went unanswered), so the app draws its own
      // muscle glyphs instead. See THIRD-PARTY-NOTICES.md.
    };
    normalised.kind = defaultSetKind(normalised);
    return normalised;
  });

  exercises.sort((a, b) => a.name.localeCompare(b.name));

  const equipment = [...equipmentSet].sort();

  mkdirSync(resolve(ROOT, 'assets/data'), { recursive: true });
  writeFileSync(resolve(ROOT, 'assets/data/exercises.json'), JSON.stringify(exercises));

  const ts = `// GENERATED by scripts/build-catalog.mjs - do not edit by hand.
// Source: ${SOURCE} (Unlicense / public domain)
// ${exercises.length} exercises.

export const MUSCLES = ${JSON.stringify(MUSCLES, null, 2)} as const;
export const CATEGORIES = ${JSON.stringify(CATEGORIES, null, 2)} as const;
export const LEVELS = ${JSON.stringify(LEVELS, null, 2)} as const;
export const FORCES = ${JSON.stringify(FORCES, null, 2)} as const;
export const MECHANICS = ${JSON.stringify(MECHANICS, null, 2)} as const;
export const EQUIPMENT = ${JSON.stringify(equipment, null, 2)} as const;

export type Muscle = (typeof MUSCLES)[number];
export type Category = (typeof CATEGORIES)[number];
export type Level = (typeof LEVELS)[number];
export type Force = (typeof FORCES)[number];
export type Mechanic = (typeof MECHANICS)[number];
export type Equipment = (typeof EQUIPMENT)[number];
`;
  writeFileSync(resolve(ROOT, 'src/catalog/generated.ts'), ts);

  if (exercises.some((e) => 'images' in e)) {
    throw new Error('Image paths leaked into the catalog - see the note above.');
  }

  const withoutInstructions = exercises.filter((e) => e.instructions.length === 0).length;
  process.stdout.write(
    `Wrote ${exercises.length} exercises, ${equipment.length} equipment types, ` +
      `${MUSCLES.length} muscles (${withoutInstructions} lack instructions).\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`build-catalog failed: ${err.message}\n`);
  process.exit(1);
});
