import { APP_URL } from '../appLink';
import { QR_MODULES, QR_URL } from '../qrMatrix';

/**
 * The QR grid is generated by scripts/build-qr.mjs and committed, so nothing here re-encodes
 * anything. What these tests protect is the two ways a committed artefact goes wrong: it stops
 * matching the link it is supposed to be, or someone hand-edits it into a grid that is no
 * longer a QR code at all.
 *
 * The encoder itself was verified against the reference implementation in `qrencode`:
 *
 *   qrencode -l M -m 0 -t ASCII 'https://grambygram.netlify.app'
 *
 * produces this grid module for module.
 */
describe('the share QR code', () => {
  it('encodes the link the rest of the app uses', () => {
    // If this fails, APP_URL changed and `npm run build:qr` was not re-run. The card would
    // otherwise go on showing a code for the old address, silently.
    expect(QR_URL).toBe(APP_URL);
  });

  it('is a square grid of a valid QR size', () => {
    const size = QR_MODULES.length;
    // Version n is 4n+17 modules across. 29 is version 3.
    expect((size - 17) % 4).toBe(0);
    expect(size).toBe(29);
    for (const row of QR_MODULES) expect(row).toHaveLength(size);
  });

  it('holds nothing but modules', () => {
    for (const row of QR_MODULES) expect(row).toMatch(/^[01]+$/);
  });

  it('carries a finder pattern in each of the three corners', () => {
    const size = QR_MODULES.length;
    const finder = [
      '1111111',
      '1000001',
      '1011101',
      '1011101',
      '1011101',
      '1000001',
      '1111111',
    ];
    const at = (top: number, left: number) =>
      finder.map((_, r) => QR_MODULES[top + r].slice(left, left + 7));

    expect(at(0, 0)).toEqual(finder);
    expect(at(0, size - 7)).toEqual(finder);
    expect(at(size - 7, 0)).toEqual(finder);
    // The fourth corner must NOT have one; that is how a scanner works out the rotation.
    expect(at(size - 7, size - 7)).not.toEqual(finder);
  });

  it('alternates along both timing lines', () => {
    const size = QR_MODULES.length;
    for (let i = 8; i < size - 8; i++) {
      const expected = i % 2 === 0 ? '1' : '0';
      expect(QR_MODULES[6][i]).toBe(expected);
      expect(QR_MODULES[i][6]).toBe(expected);
    }
  });

  it('has the always-dark module', () => {
    // Row 4*version+9, column 8. Fixed by the spec, whatever the data is.
    expect(QR_MODULES[QR_MODULES.length - 8][8]).toBe('1');
  });

  it('is neither mostly dark nor mostly light', () => {
    // A mask is chosen partly to keep this near half. Far off it means the grid is not the
    // output of a real mask-selection pass.
    const dark = QR_MODULES.join('').split('').filter((m) => m === '1').length;
    const total = QR_MODULES.length ** 2;
    expect(dark / total).toBeGreaterThan(0.4);
    expect(dark / total).toBeLessThan(0.6);
  });
});
